ahoyapi: v2
commands:

  up:
    usage: Start the docker containers.
    cmd: |
      if [ ! -d "data/db/mysql" ]; then
        mkdir -p data/db/mysql
      fi
      docker-compose up -d

  down:
    usage: Stop the docker containers.
    cmd: |
      docker-compose down

  reboot:
    usage: Stop and start the containers.
    cmd: |
      ahoy down && ahoy up

  prepare:
    usage: Prepare writh permissions within the container.
    cmd: |
      ahoy runphp cp site/sites/default/default.settings.php site/sites/default/settings.php
      ahoy permissions

  db-init: 
    usage: Initialize the database (import)
    cmd: |
      ahoy mysql drupal < database/db_instance_pro.sql
  
  db-out: 
    usage: Export database with drush.
    cmd: |
      ahoy drush sql-dump > work.sql

  db-in: 
    usage: Import database with drush.
    cmd: |
      echo "ahoy sh"
      echo "drush sql-cli < ./database/db_instance_pro.sql"
  logs: 
    usage: Display logs.
    cmd: |
      docker-compose logs -f
#
# Tools
#
  runphp:
    usage: Run a command inside a running php container.
    cmd: |
      if [ -f "docker-compose.local.yml" ]; then
        docker-compose -f docker-compose.local.yml exec web $@
        else
        docker-compose exec web $@
      fi

  mysql:
    usage: Run a Mysql command.
    cmd: |
      ahoy runphp mysql -h mysql -u root $@

  composer:
    usage: Run a Composer command.
    cmd: |
      ahoy runphp composer $@

  sh:
    use: Get shell
    cmd: |
      ahoy runphp bash
  
  drush: 
    use: Run drush command within the web container
    cmd: |
      . .env
      ahoy runphp drush --uri=$DRUPAL_BASE_URL --root=site $@

  permissions:
    use: Fix ownership and permissions
    cmd: |
      sudo chown ${USER}:${USER} ./* -R
      chmod 666 site/sites/default/settings*
      chmod a+wX site/sites/default/files -R
    